version: "3.8"
services:
  db:
    image: mongo
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:${DB_PORT}
    volumes:
      - db:/data/db
  backend:
    depends_on:
      - db
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - 8080:${NODE_PORT}
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend:/backend
      - /backend/node_modules
  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
volumes:
  db:
